minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.15.0
fabric_api_version=0.83.0+1.20.1

mod_id=ssc-hexaddon
mod_version=beta-1.0.1
maven_group=net.onixary

# 本地模组版本（与 libs 中的 jar 文件名匹配）
ssc_version=1.10.0
hexcasting_version=0.11.3

# 在线依赖版本
cloth_config_version=11.1.106
cca_version=5.2.1
inline_version=1.20.1-1.2.2-fabric
flk_version=1.13.7+kotlin.2.2.21
org.gradle.jvmargs=-Xmx4096m
org.gradle.parallel=true